### ISSUE TITLE
Add Search Functionality for Students, Professors, and Courses

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Django_StudentManagement#1]
Implement search functionality to allow users to search for students, professors, or courses by name, email, or course name.
Feature Scope:
Add search forms in the student.html, professor.html, and courses.html templates.
Modify the student, professor, and courses views to handle search queries.
Filter the results based on the search query.

**Comment by SA-10125** [comment]
Can I please work on this?

**Comment by devanshishukla17** [comment]
hi can you please assign me this

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125 60

**Comment by SA-10125** [comment]
Hey, The requirements.txt file is missing @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
Creating the requirements.txt file is a separate issue @SA-10125

**Comment by SA-10125** [comment]
(going for dinner (please dont unassign))

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125

**Comment by SA-10125** [comment]
(Thank you. Justt got back from dinner, am making some progress. Will fix your issue, not to worry.) (please don't deassign)

**Comment by SA-10125** [comment]
(Having some datbase errors with null types, fixing them by adding dummy values in the SQL shell. Working on the search function) (please don't deassign, making progress.)

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125

**Comment by SA-10125** [comment]
Thank you. Any tips on the problem (database migration errors because name is null.)

**Comment by SA-10125** [comment]
Fixed that issue, now having problems with professor model, will fix similarly.

**Comment by SA-10125** [comment]
Having error during migration, integrity error that says there's a null value in column "name" of relation "django_content_type" violates not null constraint. Any tips?

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125

**Comment by devanshishukla17** [comment]
can I please get this assigned I think I have an idea on how to fix it

**Comment by SA-10125** [comment]
Working on it almost there
almost done

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @SA-10125

**Comment by SA-10125** [comment]
thanks so much

**Comment by nikhila-kuchimanchi** [comment]
@devanshishukla17 I'll let @SA-10125 work on it and if their work isn't proper I'll assign it to you

**Comment by devanshishukla17** [comment]
okay

**Comment by nikhila-kuchimanchi** [comment]
!deassign
