### ISSUE TITLE
Add Pagination for Student, Professor, and Course Listings

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Django_StudentManagement#2]
Divide the different tables into different pages for listing students, professors, and courses to improve performance and user experience when dealing with large datasets. Add a way for the user to navigate between the various pages.

Use Django's built-in pagination in the student, professor, and courses views.
Update the templates to display the paginated results and navigation links.

**Comment by Rex-8** [comment]
can i be assigned to this

**Comment by nikhila-kuchimanchi** [comment]
!assign @Rex-8

**Comment by Rex-8** [comment]
path('student/',views.student, name='student'),
    path('courses/',views.courses, name='courses'),
    path('professor/',views.professor, name='professor'),
    
    these are the paths for the corresponding paginations right?

**Comment by nikhila-kuchimanchi** [comment]
@Rex-8 yes it's correct

**Comment by Rex-8** [comment]
bots down

**Comment by nikhila-kuchimanchi** [comment]
!assign @Rex-8

**Comment by Rex-8** [comment]
submitted a pull request

**Comment by nikhila-kuchimanchi** [comment]
!assign @Rex-8
