### ISSUE TITLE
Implement a Student Score Report

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Django_StudentManagement#4]
Develop a feature that allows students and professors to view a student's score report for all enrolled courses.
Create a new view and template to display a student's scores for all courses.
Use the Scores model to pull relevant data and display it in a report format.

Please Update README.md file accordingly with all modifications and improvements made, following the format already provided in README.

**Comment by jhalak-n** [comment]
hi can you assign this to me

**Comment by devanshishukla17** [comment]
hi can you assign this to me

**Comment by kevalpattani** [comment]
Hi, can you assign me this issue!!

**Comment by nikhila-kuchimanchi** [comment]
!assign @kevalpattani

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @kevalpattani

**Comment by namrataaravinda** [comment]
can i get this issue assigned?

**Comment by mahika34** [comment]
can i be assigned?

**Comment by mahika34** [comment]
can i be assigned

**Comment by devanshishukla17** [comment]
can I be assigned this please

**Comment by nikhila-kuchimanchi** [comment]
!assign @devanshishukla17

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @devanshishukla17

**Comment by Harshinigrandhi2005** [comment]
can u assign me @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
!assign @Harshinigrandhi2005

**Comment by Redslayer112** [comment]
please assign me @Redslayer112 -> github username

**Comment by nikhila-kuchimanchi** [comment]
!assign @Redslayer112

**Comment by DhanushSS** [comment]
pls assign me

**Comment by Harshinigrandhi2005** [comment]
im still working on it @nikhila-kuchimanchi

**Comment by Redslayer112** [comment]
deassign me please

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Harshinigrandhi2005

**Comment by Harshinigrandhi2005** [comment]
can u give ma a break now theres some midnight performances and assigne me some more time

**Comment by nikhila-kuchimanchi** [comment]
@Harshinigrandhi2005 once the timer runs out i'll assign it again to you, put a message in case I forget

**Comment by Harshinigrandhi2005** [comment]
can u assign me as the timer ran out @nikhila-kuchimanchi

**Comment by Anirudh10070** [comment]
can u please assign me this

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Harshinigrandhi2005

**Comment by nikhila-kuchimanchi** [comment]
!assign @Harshinigrandhi2005 45

**Comment by nikhila-kuchimanchi** [comment]
!assign @Harshinigrandhi2005 45

**Comment by gaganv205** [comment]
can you plz assign me!

**Comment by Boffin-Omega** [comment]
hey im done resolving this issue. can i be assigned?

**Comment by nikhila-kuchimanchi** [comment]
@Boffin-Omega yeah sure

**Comment by nikhila-kuchimanchi** [comment]
!assign @Boffin-Omega

**Comment by Boffin-Omega** [comment]
Also i came across another issue. I tried adding students, profs and courses but none of them displayed, they were added to the database. 
it makes it very hard to check if this issue is solved, unless I sign in as admin and add students manually

And when you click on professors option in the dropdown you get a template rendering error.

**Comment by nikhila-kuchimanchi** [comment]
@Boffin-Omega fork the code u currently have I'll let you know if it doesn't work, you can come meet me in person to see

**Comment by Boffin-Omega** [comment]
i couldnt fix them by myself, so if u find anything not working in student error, plis let me know

**Comment by Boffin-Omega** [comment]
alright

**Comment by Boffin-Omega** [comment]
> @Boffin-Omega fork the code u currently have I'll let you know if it doesn't work, you can come meet me in person to see

lmk when i can come

**Comment by Boffin-Omega** [comment]
can i come now?

**Comment by Boffin-Omega** [comment]
@nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
Yes @Boffin-Omega come to maintainer room

**Comment by nikhila-kuchimanchi** [comment]
!deassign
