### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Django_StudentManagement#5]
Create a requirements.txt file containing all the modules that need to be pip installed

**Comment by Rex-8** [comment]
I want to be assigned to this

**Comment by nikhila-kuchimanchi** [comment]
!assign @Rex-8

**Comment by mahika34** [comment]
can i be assigned?

**Comment by bwaklog** [comment]
@Rex-8 If you want to get assigned to another issue, please withdraw from the current one and only then apply for another.

**Comment by Rex-8** [comment]
!withdraw

**Comment by mahika34** [comment]
can i be assigned?

**Comment by shri30yans** [comment]
!deassign

**Comment by mahika34** [comment]
can i be assigned
